### ISSUE TITLE
Add Nested Array Adapter

### ISSUE THREAD

**Issue by avstudnitz** [firegento/FireGento_FastSimpleImport2#1]

**Comment by luongduy** [comment]
Is this available now?
Could you tell me how to import image like in [AvS_FastSimpleImport](https://github.com/avstudnitz/AvS_FastSimpleImport/issues/206)?
Thank you!

**Comment by EliasKotlyar** [comment]
Hello Luongduy,

>Is this available now?
This feature is not implemented yet. Feel free to contribute it by submitting a merge request.

>Could you tell me how to import image like in FastSimpleImport?
You will have to use the same Format as in the usual Backend of M2. You can also use URLs instead of a Path to the Image. Contact us if you need any more help!

Greetings
Elias

**Comment by luongduy** [comment]
Hi Elias,
Thank you very much for your response.
I tried to import with external image url, however the process stopped at `2: This file does not contain any data.`
Below is the data I used for:
```
$data[] = array(
                'sku' => 'AM1234',
                'attribute_set_code' => 'Default',
                'product_type' => 'simple',
                'product_websites' => 'base',
                'name' => 'Product 1',
                'price' => '1234',
                '_media_attribute_id' => 87,
                '_media_image' => 'http://ecx.images-amazon.com/images/I/41klcAkamSL._SL75_.jpg.jpg',
                '_media_is_disabled' => 0,
                '_media_position' => 1,
                '_media_lable' => 'Image 1',
                'image' => 'http://ecx.images-amazon.com/images/I/41klcAkamSL._SL75_.jpg.jpg',
                'small_image' => 'http://ecx.images-amazon.com/images/I/41klcAkamSL._SL75_.jpg.jpg',
                'thumbnail' => 'http://ecx.images-amazon.com/images/I/41klcAkamSL._SL75_.jpg.jpg'
)
```
Am I missing something?  Thanks in advance.

**Comment by EliasKotlyar** [comment]
Hello Luongduy,

You will have to use new column-names. They changed a little bit
base_image	
base_image_label	
small_image	
small_image_label	
thumbnail_image	
thumbnail_image_label	
swatch_image	
swatch_image_label
additional_images

Base,Small Image and Thumbnail are mostly the same thing like in M1. The field additional_images is for all the other product-images. You will have to separate their filenames with a pipe ("|").

Greetings
Elias

**Comment by EliasKotlyar** [comment]
-> Nested Adapter sucessfully added. A Demo can be found in https://github.com/firegento/FireGento_FastSimpleImport2_Demo/blob/master/Console/Command/Product/ImportConfigurable.php
