### ISSUE TITLE
Error importing products

### ISSUE THREAD

**Issue by emanueledibella** [firegento/FireGento_FastSimpleImport2#101]
Hi,
I tried to import the sample product with the code you gave in documentation:
```
/** @var \FireGento\FastSimpleImport\Model\Importer $importerModel */
$importerModel = $this->objectManager->create('FireGento\FastSimpleImport\Model\Importer');

$productsArray = [
    [
        'sku' => 'firegento-test',
        'attribute_set_code' => 'Default',
        'product_type' => 'simple',
        'product_websites' => 'base',
        'name' => 'FireGento Test Product',
        'price' => '14.0000',
    ],
];

try {
    $importerModel->processImport($productsArray);
} catch (\Exception $e) {
    $output->writeln($e->getMessage());
}

print_r($importerModel->getLogTrace());
print_r($importerModel->getErrorMessages());
```
I inserted  the code in a PHP file, but when I try to execute it I have the following error:

> PHP Fatal Error: Uncaught Error: Using $this when not in object context in test.php:2

What should I do? 
Thanks!

**Comment by jruzafa** [comment]
In your custom script not exist $this because is a script not class, for call a object manager your use a require bootstrap, more info https://magento.stackexchange.com/a/233327/165

**Comment by mrwebdesign** [comment]
Hi, thanks for your answer.
Sorry but I'm new in Magento. Could you give me an example?
Thankyou  very much!

**Comment by jruzafa** [comment]
example https://magento.stackexchange.com/questions/233284/how-do-i-run-custom-script-from-magento2-root-folder/233327#233327 


Greetings!

**Comment by mrwebdesign** [comment]
Hi, I tried but it doesn't work.
It doesn't give me an error, in fact it seems that everything is working, but when I check if my imported product is in catalog, I don't see it.

**Comment by sprankhub** [comment]
https://github.com/firegento/FireGento_FastSimpleImport2_Demo/ has quite some examples.
