### ISSUE TITLE
Clear Field on Symbol - Correspondent from Magento 1

### ISSUE THREAD

**Issue by capimichi** [firegento/FireGento_FastSimpleImport2#103]
Does Fast simple import for M2 have a correspondent option to get this result?

![Schermata 2020-02-21 alle 09 34 25](https://user-images.githubusercontent.com/23385107/75017504-721f5780-548d-11ea-8e55-601481fb405f.png)

Thanks

**Comment by avstudnitz** [comment]
Sorry, no.
