### ISSUE TITLE
Error: ["Error in data structure: entity values are mixed"] []

### ISSUE THREAD

**Issue by AshishBhatia89** [firegento/FireGento_FastSimpleImport2#116]
Hi Team,

We are getting entity values are mixed while importing the products. Would you please guide us how to trace the root cause of "Error: ["Error in data structure: entity values are mixed"] []"?

Regards,
Ashish

**Comment by sprankhub** [comment]
This error is independent of our module. You have to debug into the method, where this error is thrown (`\Magento\ImportExport\Model\ResourceModel\Import\Data::getUniqueColumnData`) and analyse from there.
