### ISSUE TITLE
 Deprecated Functionality: Optional parameter $delimiter declared before required parameter $string

### ISSUE THREAD

**Issue by ajaysingh-webkul** [firegento/FireGento_FastSimpleImport2#123]
Deprecated Functionality: Optional parameter $delimiter declared before required parameter $string is implicitly treated as a required pa  
  rameter in /home/users/ajay.singh/www/html/244/vendor/firegento/fastsimpleimport/Model/Import/Category.php on line 1066      

Magento version:- 2.4.4

Issue:- Getting  this issue while running php bin/magento setup:di:compile

php version: 8.1

**Comment by ajaysingh-webkul** [comment]
Fixed issue zip

change file:- Model/Import/Category.php
[Model.zip](https://github.com/firegento/FireGento_FastSimpleImport2/files/8651019/Model.zip)


Because in php8.1, named parameters were added. This means that from now, parameters without a default value, are required to be BEFORE optional parameters.

**Comment by sprankhub** [comment]
See #122 / #121 / #120.

**Comment by se45ky** [comment]
@sprankhub there's a way to speed up it?

**Comment by sprankhub** [comment]
Could you please check if [version 2.0.0](https://github.com/firegento/FireGento_FastSimpleImport2/releases/tag/2.0.0) solves the issue for you?
