### ISSUE TITLE
catalog_product_link row disappears when updating product

### ISSUE THREAD

**Issue by matteorossi-thespacesm** [firegento/FireGento_FastSimpleImport2#127]
Hello,

we have found a really strange behaviour: when we try and update a product data (fields status, visibility, qty, is_in_stock, date_update), product links disappear from catalog_product_link table. Specifically upsell product link related to the product which is updated.
My update code does not refer in any way to product links and I can't understand such behaviour.

**Comment by sprankhub** [comment]
Which version of the module do you use? Can you include an example, which causes the issue?

**Comment by matteorossi-thespacesm** [comment]
Hello, we have discovered that such behavior is not related to fastsimpleimport, but link processor class of import product module.
If an import array does not include links, in ADD_UPDATE behavior existing links are erased; in APPEND mode they are deleted than created again, thus incrementing catalog_product_link ids.

**Comment by sprankhub** [comment]
Thanks for the feedback. Then I guess we can close this :)
