### ISSUE TITLE
Deprecated Functionality: mb_check_encoding()

### ISSUE THREAD

**Issue by se45ky** [firegento/FireGento_FastSimpleImport2#129]
Deprecated Functionality: mb_check_encoding(): Calling mb_check_encoding() without argument is deprecated in /var/www/html/vendor/magento/module-import-export/Model/Import/AbstractEntity.php on line 438

**Comment by sprankhub** [comment]
This function is not called in this extension. It looks like it comes from core code. However, even in the core, it seems to be [called with an argument nowadays](https://github.com/magento/magento2/blob/5dc13c3d81c0aa7164b06c08980aef4b779388a6/app/code/Magento/ImportExport/Model/Import/AbstractEntity.php#L449), maybe you use an old version?
