### ISSUE TITLE
Protected to private method convert

### ISSUE THREAD

**Issue by nikunjkaccorin** [firegento/FireGento_FastSimpleImport2#130]
Hi Team,
what is reason to convert protected method private?
vendor/firegento/fastsimpleimport/Model/Import/Category.php

**Comment by sprankhub** [comment]
See [number 2.7 of the Technical Guidelines](https://developer.adobe.com/commerce/php/coding-standards/technical-guidelines/#2-class-design):

> 2.7. All non-public properties and methods SHOULD be private.

So the reason for doing this is to follow Magento technical guidelines :)

If you have a use case, where you think the module cannot be extended properly any more, feel free to share a concrete example, preferably as a new issue.
