### ISSUE TITLE
Error on calling processImport a second time

### ISSUE THREAD

**Issue by mfickers** [firegento/FireGento_FastSimpleImport2#133]
After upgrading this extension to version 2, our custom product import broke.

We are parsing XML files containing 10000 products each and importing this data using \FireGento\FastSimpleImport\Model\Importer::processImport for every file. For the first file, the import behaves as expected, but when calling processImport a second time, we get this error during validation of the first row:
`Warning: Trying to access array offset on value of type null in /var/www/magento/vendor/magento/module-catalog-import-export/Model/Import/Product.php on line 1270`
## Environment
PHP 8.1
Magento 2.4.5-p1
FastSimpleImport 2.0.1

## Steps to reproduce
Call \FireGento\FastSimpleImport\Model\Importer::processImport on the same object twice, with different products each.
Behavior is set to BEHAVIOR_ADD_UPDATE and all products exist already.

## Expected behavior
Products from both calls are imported

## Actual behavior
Importer will throw an exception: "Error in data structure: entity values are mixed".
ErrorAggregator will contain an error message: "Warning: Trying to access array offset on value of type null in /var/www/magento/vendor/magento/module-catalog-import-export/Model/Import/Product.php on line 1270"

## Additional information
I've debugged through the process and found that \Magento\ImportExport\Model\Import\Entity\AbstractEntity::$_validatedRows is not reset between the first call of \FireGento\FastSimpleImport\Model\Importer::importData and the second call of \FireGento\FastSimpleImport\Model\Importer::validateData. 

This means during validation for the second call to processImport, all rows are already marked as valid and some key logic will be skipped.

[This commit](https://github.com/firegento/FireGento_FastSimpleImport2/commit/3e391398228b51a69fa9a263e65c80baeb88d8bd) seems to be the one that introduced this behavior, as prior to that a new import model was created before validation.

**Comment by simthax** [comment]
Got this error too and had to add the following patch to avoid this issue

```
+++ b/vendor/firegento/fastsimpleimport/Model/Importer.php
@@ -53,6 +53,7 @@ class Importer
      */
     public function processImport(array $dataArray): void
     {
+        $this->importModel = null;
         $this->validateData($dataArray);
         $this->importData();
     }
```
