### ISSUE TITLE
Problem importing large batches

### ISSUE THREAD

**Issue by Sennep1** [firegento/FireGento_FastSimpleImport2#135]
Hi, 

We're having issues with your module trying to import several thousands of products, split into batches of 600.
Updated products just don't get updated in Magento even though the array input clearly has the required changes. The module does process all products but updates just aren't going through.
We are currently using version 1.3.1 as 1.3.4 throws errors regarding the Magento link processor. 

Example code for the import:
`        
foreach ($batches as $batch) {
            /** @var \FireGento\FastSimpleImport\Model\Importer $importerModel */
            $importerModel = $this->importerFactory->create();

            try {
                $importerModel->processImport($batch);
            } catch (\Exception $e) {
                print_r($e->getMessage());
            }

            $this->log[] = $importerModel->getLogTrace();
            $this->log[] = $importerModel->getErrorMessages();

            print_r($importerModel->getLogTrace());
            print_r($importerModel->getErrorMessages());
}

Example products array with 1 product:

```
Array
(
    [0] => Array
        (
            [sku] => 5407009981050
            [attribute_set_code] => Default
            [product_type] => simple
            [product_websites] => base
            [name] => product name
            [subtitle] => 
            [price] => 19.95
            [tax_class_id] => 7
            [url_key] => product-name
            [description] => Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris ligula, porttitor eget luctus non, ullamcorper viverra libero. Mauris facilisis nisi lectus, sit amet fringilla arcu placerat vel.
            [image] => 
            [small_image] => 
            [thumbnail] => 
            [additional_images] => 
            [categories] => Products/Books
            [language] => und
            [publish_date] => 
            [press] => 
            [preview_pages] => 11
            [width_cm] => 166
            [length_cm] => 166
            [depth_cm] => 35
            [weight_text] => 422
            [number_pages] => 
            [author] => 
            [illustrator] => 
            [series] => 
            [format] => Hardcover
            [nur] => Non fiction
            [publishing_status] => 04: Active
            [product_availability] => 21: In stock
            [type_of_product] => Book
            [status] => 1
            [theme] => games
        )

    [1] => Array
        (
            [sku] => 5407009981050
            [attribute_set_code] => Default
            [product_type] => simple
            [product_websites] => store_nl
            [store_view_code] => nl_nl
            [tax_class_id] => 7
        )

    [2] => Array
        (
            [sku] => 5407009981050
            [attribute_set_code] => Default
            [product_type] => simple
            [product_websites] => store_rw
            [store_view_code] => en_rw
            [tax_class_id] => 7
        )
)


Can you please advise?

**Comment by sprankhub** [comment]
Are no products updated? Or only some products? Since when does the issue happen? What did you change?

In general, I advise updating to the latest version 2.x.

**Comment by sprankhub** [comment]
Closing due to lack of feedback.
