### ISSUE TITLE
Imported resource (image) could not be downloaded from external resource due to timeout or access permissions

### ISSUE THREAD

**Issue by mattiaguatta** [firegento/FireGento_FastSimpleImport2#139]
hello,

i uploaded an image on pub/media/import/ but still have this error on magento 2.4.5, any solutions?

thanks

**Comment by sprankhub** [comment]
Please give a bit more details. Which PHP version, which Magento version, exact path to image, array that you try to import, code you run to import ...

**Comment by mattiaguatta** [comment]
hello,

php8.1
magento 2.4.5-p1
image path public_html/pub/media/import/64134.jpg

array that i send to  $importerModel->processImport($data); is

`Array
(
    [0] => Array
        (
            [sku] => SR200AE
            [product_type] => simple
            [url_key] => sr200ae-satinatrice-SR200AE
            [attribute_set_code] => macchine_utensili
            [product_websites] => base
            [categories] => Default Category/Macchine Utensili/Utensili a filo/Altri Utensili a filo
            [name] => SR200AE SATINATRICE
            [product_online] => 2
            [visibility] => Catalog, Search
            [tax_class_id] => 2
            [is_in_stock] => 1
            [use_config_manage_stock] => 0
            [manage_stock] => 1
            [base_image] => 64134.jpg
            [small_image] => 64134.jpg
            [thumbnail_image] => 64134.jpg
            [additional_images] => 64134.jpg
            [swatch_image] => 64134.jpg
            [url_key_create_redirect] => 1
            [save_rewrites_history] => 1
            [syrio_prezzo_acquisto] => 243.500000
            [price] => 427.8
            [special_price] => 
        )

)`

**Comment by mattiaguatta** [comment]
> Please give a bit more details. Which PHP version, which Magento version, exact path to image, array that you try to import, code you run to import ...

I use the same import code on other magento 2.4.5-p1 in the same server, with the same php8.1 and not have any issue

**Comment by mattiaguatta** [comment]
> Please give a bit more details. Which PHP version, which Magento version, exact path to image, array that you try to import, code you run to import ...

you have same error? can help me to resolve it?

**Comment by sprankhub** [comment]
If the same code works on another server, then the issue is indeed system-specific. It is hard to help in this case. As the error message suggests, I would check permissions on the respective files / directories. Also, you might want to debug into `\Magento\CatalogImportExport\Model\Import\Product::_saveProducts`, where the respective error message is thrown.
