### ISSUE TITLE
Category URL key for specified store already exists on multi-website

### ISSUE THREAD

**Issue by fokkejan-made-by-mouses** [firegento/FireGento_FastSimpleImport2#142]
Good afternoon,

We're having trouble importing categories on a multi-website installation. We automatically create categories per website from an external system. Every website has its own category tree in Magento.

The problem is that if the category has the same name for both websites, the URL key will also be the same.
For example, the category 'Non-Food -> Papier/Karton': https://mous.es/WnysYz.png. This name is the same for both Dutch and German.
When that happens, this error is given: URL key for specified store already exists.

In vendor/magento/module-catalog/Model/Category.php we see code that is likely causing this problem.
The `getStoreIds()` method always returns the default store ID (from the default category tree). However, you would only want the store_id of the associated category tree.

Can this be resolved?
I hope my question is clear enough.

This is the data we pass through \FireGento\FastSimpleImport\Model\Importer::processImport():
```
[
    '_root'             => $rootCategory->getName(),
    '_category'         => $headCategoryName . '#' . $subCategoryName,
    'name'              => $subCategoryName,
    'description'       => '',
    'is_active'         => true,
    'include_in_menu'   => true,
    'meta_description'  => $subCategoryName,
    'url_key'           => $subUrlKey,
    'available_sort_by' => false, // use all available choices
    'default_sort_by'   => 'position',
]
```
`$rootCategory` is the head category of the category tree, depending on the website.

**Comment by sprankhub** [comment]
Wouldn't you need to add `_store` to the data? Does that fix your issue by chance?

**Comment by henkvalk** [comment]
Is there a specific reason to create the same category structure twice, instead of using the scope? Just wondering

**Comment by fokkejan-made-by-mouses** [comment]
@sprankhub Thanks, that was the fix for the problem. 
I didn't know the option was there.
This issue can be closed then.

@henkvalk We use different category structures because not the entire structure is the same. Some of them has the same category path, and also the same names. But the most categories are different for Dutch and German.
