### ISSUE TITLE
Import Failed With message "Please enter a correct entity model". Any Suggestion ?

### ISSUE THREAD

**Issue by svaapta** [firegento/FireGento_FastSimpleImport2#2]
/public_html/ves_yume_magento$ /opt/lampp/bin/php bin/magento fastsimpleimport2demo:products:importsimple
Import started
**Please enter a correct entity model.**
1: Begin data validation
Import finished. Elapsed time: 0.8s

**Comment by EliasKotlyar** [comment]
Hello,

Many thanks for your contribution. I tried to reproduce it,but failed. The Code at my machine is running correct. For further reproducing this issue , we need to get some information about your installation:

-> Which Magento2 version are you using? 
-> Do you have modified the code of the plugin? If so,please provide the changes.


Best Regards,
Elias

**Comment by svaapta** [comment]
Hello Elias,

Let me provide you the information as per your question.

-> Which Magento2 version are you using? 
[Svaapta] : Magento ver. 2.0.2

-> Do you have modified the code of the plugin? If so,please provide the changes.
[Svaapta] : Nothing have been modified.Just done extension installations and tried the command.

Regards,
Svaapta

**Comment by EliasKotlyar** [comment]
Hello Svaapta,

I still cannot reproduce this issue. Can you please provide additional information:
1. Which PHP-Version are you running?
2. How did you install M2(composer,git clone?)? Are you running Community or Enterprise?
3. Which modules are installed in your System?(provide please the composer.json )
4. How did you install the Modules?(copied, or using composer?)

Greetings
Elias

**Comment by svaapta** [comment]
Hello Elias,

Please review the answers as below.

I still cannot reproduce this issue. Can you please provide additional information:
1. Which PHP-Version are you running?
[Svaapta] : PHP Version 5.5.11
                  System	Linux IT-ALLY-19 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64

2. How did you install M2(composer,git clone?)? Are you running Community or Enterprise?
[Svaapta] : Running Community version on localhost. The quick starter of free resource theme http://www.venustheme.com/magento-2-template/

3. Which modules are installed in your System?(provide please the composer.json )
[Svaapta] : Modules List : ExtendedImport, FastSimpleImport2, FastSimpleImport2Demo
                  Location of modules :           /home/myusername/public_html/ves_yume_magento/app/code/FireGento
All composers files are the same as the modules available on Github.

4. How did you install the Modules?(copied, or using composer?)
[Svaapta] : Copied all modules to app/code/FireGento
                  Run magento following commands : php bin/magento setup:upgrade
                                                                            php bin/magento cache:clear
                                                                            php bin/magento cache:flush

I would like to also know if the error statement itself point to the some code error where i can debug and fix from my end. Right now i have no direction about what's the statement meaning.

Regards,
Svaapta

**Comment by EliasKotlyar** [comment]
Hello,

I am investigating it, and now run into a similar error. My Error has something to do with the ExtendedImport Plugin. More info will come as soon as i get to any results.

Please try disabling the ExtendedImport Plugin. It is not required for the Demo-Import.

Here is the command for disabling it:
bin/magento module:disable FireGento_ExtendedImport

Please report if it will fix the issue.

Greetings
Elias

**Comment by svaapta** [comment]
Hello Elias,

Sorry but there is no any changes affected even if i have disabled the module.

Steps what i have followed
1) /public_html/ves_yume_magento$ /opt/lampp/bin/php bin/magento module:disable -c FireGento_ExtendedImport
The following modules have been disabled:
- FireGento_ExtendedImport

Cache cleared successfully.
Generated classes cleared successfully. Please re-run Magento compile command
Generated static view files cleared successfully.
2) /public_html/ves_yume_magento$ /opt/lampp/bin/php bin/magento setup:upgrade
3) /public_html/ves_yume_magento$ /opt/lampp/bin/php bin/magento cache:clean
4) /public_html/ves_yume_magento$ /opt/lampp/bin/php bin/magento cache:flush
5) /public_html/ves_yume_magento$ /opt/lampp/bin/php bin/magento fastsimpleimport2demo:products:importsimple
Import started
Please enter a correct entity model.
1: Begin data validation
Import finished. Elapsed time: 0.6s

Let me also tell you i have also tried to remove extension directory but its still same error message.

Regards,
Svaapta

**Comment by EliasKotlyar** [comment]
Hello Svaapta,

I have tried it with this VES-Demo and i still cannot reproduce it. Regarding the "ExtendedImport" Plugin, it was a "naming" issue from my side. I done a mistake , by naming the folder wrong, and it has led to strange behaviour of this plugin. 

I have included now a Screenshot of my directory Structure. Could you please verify if you have the same directory structure? 

![Uploading Bildschirmfoto_2016-03-29_14-27-04.png…]()

Also: Which M2 mode are you currently running? Please use developer mode instead of default:
http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html

Can you please also provide your Log Files? They should be in  var/log . Especially the File  var/log/exception.log is important.

Greetings
Elias

**Comment by svaapta** [comment]
Hello Elias,

Just attached the directory structure and log file what you have asked to look for. Please check and let me know if you have any clue about the error.

I have change the mode to developer one and clean the cache and compiled the magento again but its still error message.
![directory-structure](https://cloud.githubusercontent.com/assets/16476532/14134030/9b81bc04-f671-11e5-9589-0de592572125.png)

[exception (copy).docx](https://github.com/firegento/FireGento_FastSimpleImport2/files/194953/exception.copy.docx)

Regards,
Svaapta

**Comment by EliasKotlyar** [comment]
Hello Svaapta,

As far as i see , you have the module FireBear/ImportExport installed.
(https://github.com/firebearstudio/importexport)
Could you please try to disable it?

Greetings
Elias

**Comment by svaapta** [comment]
Hello Elias,

Great !! Its works now. So it means there some is conflict with the extensions each other.

Regards,
Svaapta

**Comment by imtiaz0405** [comment]
Hi , 
I have the same issue  and in my  case i found the module ImageMagick was missing .
i found this in exception logs .

you can install this by
yum -y install ImageMagick-devel ImageMagick-c++-devel ImageMagick-perl

**Comment by arshadpkm** [comment]
Please give write permission to var folder in Magento root and check
