### ISSUE TITLE
Trying to Import Category but i am not able to download Sample CSV File

### ISSUE THREAD

**Issue by punitgadhiya** [firegento/FireGento_FastSimpleImport2#21]
Hi, I want to import category through your extension but I am not able to download CSV format. Can you please provide the format of CSV for Category Import?

Thanks

**Comment by EliasKotlyar** [comment]
Hello punitgadhiya,

I have inserted the sample File to the "Files/Sample" Directory. Unfortunately Magento2 is unable to recognize this file and provide a download in the backend. I have created issue on the M2 repository:
https://github.com/magento/magento2/issues/6553

Greetings
Elias

**Comment by punitgadhiya** [comment]
Hi EliasKotlyar,

Thanks for your answer. Though yesterday I make CSV myself. but there is one issue if we set 1 for `include_in_menu` and `is_active` it shows disable and when we keep it blank then it shows enable. so, currently I am making above fields of CSV blank (without value) works fine for me.

**Comment by punitgadhiya** [comment]
Hi EliasKotlyar,

![2016-09-15_1932](https://cloud.githubusercontent.com/assets/4026578/18552708/3f73402e-7b7b-11e6-8d0f-f39a03c6e16c.png)

after importing category it remains to disable any idea? reindex also not works if we do 2nd-time import empty value in `include_in_menu `and` is_active` it shows button enable but yet category is light and not shows in front-end any idea?

**Comment by EliasKotlyar** [comment]
Hello punitgadhiya,

Thanks for your Bug Report. I could reproduce the bug. Attributes "is_active" and "include_in_menu" were not imported correctly. I have provided a bugfix for this issue. Please update to the latest version and try again.

Greetings
Elias

**Comment by punitgadhiya** [comment]
Hi Elias,

Thanks for your quick reply. yes "is_active" and "include_in_menu" works fine now. but once we import category it is not shown in front-end menu till we do not save category from admin. do you have any idea?

**Comment by EliasKotlyar** [comment]
Hello punitgadhiya,

After you have made an import, you have to clean at least following caches:
COLLECTION_DATA 
BLOCK_HTML 
FPC 

After you cleaned them, you should be able to see the changes. 

Greetings
Elias

**Comment by punitgadhiya** [comment]
Hi Elias,
 Yes I did try to remove all caches and also did reindex but not works

**Comment by EliasKotlyar** [comment]
Hello punitgadhiya,

I cannot reproduce it. Could you please describe what exactly you are importing? I have tested here with the default import, and its working without problems.

Greetings
Elias
