### ISSUE TITLE
Mass product importing. How to?

### ISSUE THREAD

**Issue by WillColl** [firegento/FireGento_FastSimpleImport2#22]
Hi. Hey. Is it possible in this module massively import products using only one time processImport() without using foreach?

**Comment by EliasKotlyar** [comment]
Hello WillColl, 

Please take a look at the  Demo Module:
https://github.com/firegento/FireGento_FastSimpleImport2_Demo

With it you should be able to implement that.

Greetings
Elias

**Comment by WillColl** [comment]
Using FireGento_ExtendedImport2 (ported from AvS_FastSimpleImport) is not a better solution?

**Comment by EliasKotlyar** [comment]
No. Firegento_ExtendedImport2 is just a module which improves the import by adding several features. It cannot be used alone to import data.

**Comment by WillColl** [comment]
Now i see example of usage in Demo Module. Thanks for advice. 
Last question. Do you know, whether the cron jobs is working properly by using abstract class?

**Comment by EliasKotlyar** [comment]
Hello WillColl,

Unfortunately we cannot provide support for general questions. I would recommend you to ask this type of questions on StackExchange. But : Feel free to report any issue regarding to the "Firegento_Fastsimpleimport" here.

Greetings
Elias
