### ISSUE TITLE
is_active and in_header field in category import

### ISSUE THREAD

**Issue by ZebraBeard** [firegento/FireGento_FastSimpleImport2#25]
I`m try to import categories, and even if is_active and in_header field set to 1, it become not active after import.

**Comment by EliasKotlyar** [comment]
Hello ZebraBeard,

Could you please provide additional information? Which Magento Version are you using, which FireGento FastSimpleImport2 Version?

Please try it with the current master-branch, because there was a lot of refactoring on the category import.

Greetings
Elias

**Comment by ZebraBeard** [comment]
Hello. I`m using Magento 2.0.6, last Firegento FSI version, update just today.

**Comment by EliasKotlyar** [comment]
Hello ZebraBeard,

I have corrected an issue with a dependency. Could you please try again with the newest Version? My tests were very positive.

Greetings
Elias

**Comment by ZebraBeard** [comment]
Hello @EliasKotlyar 
No, it does not help. But i found root of problem.
firegento/fastsimpleimport/Model/Import/Category.php
line 1004
Because of this fields is "select" type it will become "Yes" or "No" on this line. And this field is int in a database, so it just become 0 ((int)"Yes" = 0).

**Comment by EliasKotlyar** [comment]
Hello Zebrabeard,

Please take a look at the Code at 
https://github.com/firegento/FireGento_FastSimpleImport2/blob/master/Model/Import/Category.php#L116

There was an fix, to correct a similar issue. 

Greetings
Elias

**Comment by ZebraBeard** [comment]
Oh, yeah. Now i see. In some case my extension don`t update to the latest version via composer. 
Thanks guys. You are awesome.
