### ISSUE TITLE
Product import, assigning to category not working 

### ISSUE THREAD

**Issue by EvanRijn** [firegento/FireGento_FastSimpleImport2#3]
Hi first of all :) Great extension, and great that it is already ready for 2 !

I'm trying to import the products and asign them to a category, the import is fine but the category linking is not working.

My test array last record:
  [464]=>
  array(20) {
    ["sku"]=>
    string(31) "companyx-polo-white"
    ["category"]=>
    string(23) "Default Category/Shirts"
    ["attribute_set_code"]=>
    string(7) "Default"
    ["product_type"]=>
    string(12) "configurable"
    ["product_websites"]=>
    string(4) "base"
    ["website_id"]=>
    string(1) "1"
    ["name"]=>
    string(35) "name product companyx"
    ["price"]=>
    string(5) "85.00"
    ["weight"]=>
    string(1) "1"
    ["configurable_variation_labels"]=>
    string(5) "Color"
    ["description"]=>
    string(50) "Description of. "
    ["product_online"]=>
    string(1) "1"
    ["visibility"]=>
    string(15) "Catalog, Search"
    ["base_image"]=>
    string(69) "http://cdn.companyx.com/image/cache/data/white-600x600.jpg"
    ["small_image"]=>
    string(69) "http://cdn.companyx.com/image/cache/data/white-600x600.jpg"
    ["thumbnail_image"]=>
    string(69) "http://cdn.companyx.com/image/cache/data/white-600x600.jpg"
    ["qty"]=>
    string(1) "0"
    ["is_in_stock"]=>
    string(1) "1"
    ["additional_attributes"]=>
    string(32) "has_options=1,required_options=1"
    ["configurable_variations"]=>
    string(182) "sku=companyx-polo-white-S,size=S|sku=companyx-polo-white-M,size=M|sku=companyx-polo-white-L,size=L|sku=companyx-polo-white-XL,size=XL|"
  }

I dont' get any errors, but the product is not assigned to the category. Do you have any idea where i can dig? To find the problem ;)

Regards,
Erik

**Comment by EliasKotlyar** [comment]
Hello Erik,

The Array-Key for Category is "categories" and not "category". About "digging" to the right Format:  
Consider using the Import/Export Functionality in the Backend. Its the same API which this Plugin is using.

Greetings
Elias

**Comment by EvanRijn** [comment]
Thank you Elias, i feel very stupid :)
