### ISSUE TITLE
Importing categories with specific names for storeview values creates duplicate category

### ISSUE THREAD

**Issue by koenner01** [firegento/FireGento_FastSimpleImport2#30]
When trying to import category data that contains seperate names for storeview values, duplicate categories will be created everytime you import the same data. The same issue occurs if you import admin values and change the category name manually in the backend for a specific storeview.

I traced this issue back to \FireGento\FastSimpleImport\Model\Import\Category;
The getCollection function returns a collection with store id equal to the default store id.

```
    protected function getCollection()
    {
        return $this->categoryCollection->addNameToResult();
    }
```

On the next import that collection will contain the values for the default storeview instead of the admin values. The code should be changed to 

```
    protected function getCollection()
    {
        return $this->categoryCollection->setStoreId(0)->addNameToResult();
    }
```

Because we want the import to be based on the admin values.

**Comment by EliasKotlyar** [comment]
Hello koenner01,

Thanks you for reporting this issue. I have validated it, and inserted the fix. 

Greetings
Elias
