### ISSUE TITLE
CategoryImportVersion requires EE in order to work

### ISSUE THREAD

**Issue by leptoquark1** [firegento/FireGento_FastSimpleImport2#32]
Staging is not available in the Community Edition, so the dependency injection compilation failed because 

> Magento\Staging\Model\VersionManager
> Magento\Staging\Model\ResourceModel\Db\ReadEntityVersion

 is not found caused by [CategoryImportVersion](https://github.com/firegento/FireGento_FastSimpleImport2/blob/master/Model/Enterprise/CategoryImportVersion.php).

**Comment by EliasKotlyar** [comment]
Hello leptoquark1,

Thanks you for reporting this issue. I have validated it, and inserted a fix.

Greetings
Elias
