### ISSUE TITLE
running setup:di:compile in production gives ReflectionException

### ISSUE THREAD

**Issue by koenner01** [firegento/FireGento_FastSimpleImport2#33]
I'm trying to deploy the module on a MG2.1 CE running in production mode but when it runs the setup:di:compile, a ReflectionException is thrown.

```
[ReflectionException]
  Class Magento\Staging\Model\VersionManager does not exist
```

The only reference to this I could find on the MG2 github was https://github.com/magento/magento2/issues/5350, but the module doesn't run any setup scripts so it's probably not very related.

**Comment by EliasKotlyar** [comment]
Hello Koenner01,

Could you please check which Version of the Plugin you are using? We had the same issue a day ago(https://github.com/firegento/FireGento_FastSimpleImport2/issues/32), which is already corrected.

Greetings
Elias

**Comment by koenner01** [comment]
I updated the codebase yesterday evening, seeing as you fixed 2 of my reported issues :).
Should be the latest code on the master branch

**Comment by koenner01** [comment]
Nevermind your fix was right after when I updated :)
