### ISSUE TITLE
Can't import custom_options

### ISSUE THREAD

**Issue by samueletraianus** [firegento/FireGento_FastSimpleImport2#37]
Hello, I got an issue with custom_options.
I create a string that looks like the export:
```
name=test,type=drop_down,required=1,price=1.0000,price_type=fixed,option_title=var 1

name=test,type=drop_down,required=1,price=1.0000,price_type=fixed,option_title=var 1|name=test,type=drop_down,required=1,price=2.0000,price_type=fixed,option_title=var 2
```

Array:
```
$data[] = array(
    'sku' => 'FIREGENTO-1',
    'attribute_set_code' => 'Default',
    'product_type' => 'simple',
    'product_websites' => 'base',
    'name' => 'FireGento Test Product 1',
    'price' => '14.0000',
    'ean' => "1234",
    'color' => "PurpleBlue"
    'custom_options' => 'name=test,type=drop_down,required=1,price=1.0000,price_type=fixed,option_title=var 1'
);

$data[] = array(
    'sku' => 'FIREGENTO-2',
    'attribute_set_code' => 'Default',
    'product_type' => 'simple',
    'product_websites' => 'base',
    'name' => 'FireGento Test Product 2',
    'price' => '14.0000',
    'ean' => "1234",
    'color' => "PurpleBlue"
    'custom_options' => 'name=test,type=drop_down,required=1,price=1.0000,price_type=fixed,option_title=var 1|name=test,type=drop_down,required=1,price=2.0000,price_type=fixed,option_title=var 2'
);
```

This will actually not work.
If I import an csv with custom_options, it work's perfectly.

Console Error:
1: Begin data validation
2: This file does not contain any data.

So, am I doing something wrong?

**Comment by samueletraianus** [comment]
Additional Problem
If I set custom_options blank, the custom_option will not empty (product).

**Comment by EliasKotlyar** [comment]
Hello ssamueletraianus,

You should disable the nested array support(uncomment it in the deme) or provide the data as Array.

Contact me if you need further information.

Greetings
Elias

**Comment by max21** [comment]
I just use the https://github.com/firegento/FireGento_FastSimpleImport2_Demo and I've got the same error.
I'm not sure to undestand what I have to do to resolve this issue.
