### ISSUE TITLE
Nested arrays not working

### ISSUE THREAD

**Issue by domeglic** [firegento/FireGento_FastSimpleImport2#44]
There is no option that I can see to enable nested arrays? The only way I see is to add a new preference for **ImportAdapterFactoryInterface** that uses the nested array factory.

However even after that, the nested array adapter is not correctly setting the data. It sets the values using the format **key=value1,key=value2**.

**Comment by EliasKotlyar** [comment]
Hello Domeglic,

Please have a look at the demo module:
https://github.com/firegento/FireGento_FastSimpleImport2_Demo/blob/master/Console/Command/AbstractImportCommand.php

I have tested the Nested-Array-Adapter and it was working fine.

I hope i could help you,
Greetings
Elias

**Comment by domeglic** [comment]
Ah I see, there is now a different format for multi values and for bundle/configurable.
