### ISSUE TITLE
Error Importing products

### ISSUE THREAD

**Issue by saghun** [firegento/FireGento_FastSimpleImport2#45]
Hello,
Basically i tried with your example:
`/** @var \FireGento\FastSimpleImport\Model\Importer $importerModel */
$importerModel = $this->objectManager->create('FireGento\FastSimpleImport\Model\Importer');

$productsArray = [
    [
        'sku' => 'firegento-test',
        'attribute_set_code' => 'Default',
        'product_type' => 'simple',
        'product_websites' => 'base',
        'name' => 'FireGento Test Product',
        'price' => '14.0000',
    ],
];

try {
    $importerModel->processImport($productsArray);
} catch (\Exception $e) {
    $output->writeln($e->getMessage());
}

print_r($importerModel->getLogTrace());
print_r($importerModel->getErrorMessages());`
And not works. Magento 2 throw me the error:
Fatal error: Uncaught Error: Call to a member function getName() on null in .../vendor/magento/module-catalog-import-export/Model/Import/Product/CategoryProcessor.php on line 80

And i don't know why it's fail. It's the starting point and i tried to fill the array with other data but nothing works, so... what can i do?

**Comment by phrench** [comment]
I suggest to give the demo extension a try to get a head start:
https://github.com/firegento/FireGento_FastSimpleImport2_Demo/
