### ISSUE TITLE
category not assigned with product import

### ISSUE THREAD

**Issue by amitphpdeveloper** [firegento/FireGento_FastSimpleImport2#46]
I passed below product data array.

$data[] = array(
                'sku' => 'test4',
					'attribute_set_code' => 'Bottom',
					'product_type' => 'simple',
					'product_websites' => 'base',
					'name' => 'Test Product2',
					'price' => '1000',
					'visibility' => 'Catalog, Search',
					'tax_class_name' => 'Taxable Goods',
					'product_online' => '1',
					'weight' => '1.0000',
					'short_description' => 'short description',
					'description' => 'long description',
					'qty' => 120,
					'is_in_stock' => 'in_stock',
					'color' => 'Red',
					'size' => 32,
					'category_ids' => array('Gear','7',9),
            );

tried everything with category ids data, but facing problem "This file does not contain any data. " if i remove category_ids then it works.

**Comment by avstudnitz** [comment]
Did you activate "nested array" support in the configuration?

**Comment by amitphpdeveloper** [comment]
I don't see such kind of configuration setting in admin panel. I have implemented "FireGento_FastSimpleImport"  and "FireGento_FastSimpleImportDemo"  module

**Comment by VincentMarmiesse** [comment]
Hello @amitphpdeveloper,

I don't know if you still have the issue, but it works for me with this:
```
'categories' => 'Default Category/Category 1|Default Category/Category 2'
```

So `categories` instead of `category_ids` and the categories names from the root category separated by `|`.

**Comment by amitphpdeveloper** [comment]
Hello VincentMarmiesse,

Apologize for late reply

I have applied categories as mentioned but it creates new category and assign that product to new category. I tried with existing category name and ids but it creates new category every time.

I am close to solve this issue. 

Thanks 
Amit

**Comment by amitphpdeveloper** [comment]
Hello VincentMarmiesse,

The issue has been fixed, For existing category use below format

`"categories" : "Default Category/Gear,Default Category/Gear/Bags"`

Hope it helps to others

Thanks
Amit
