### ISSUE TITLE
Import category with a "/" in its name

### ISSUE THREAD

**Issue by VincentMarmiesse** [firegento/FireGento_FastSimpleImport2#48]
Hello,

I'm trying to import a category with a "/" in its name, ie "Mouses / Keyboards", but the import thinks Mouses is its parent which obviously does not exist.

Is it possible to do it?

Thanks!

**Comment by avstudnitz** [comment]
In Magento 1, you had to add a backslash before the slash. In your example: "Mouses \/ Keyboards". Could you try that and report back?

**Comment by VincentMarmiesse** [comment]
Indeed, it works!
Thanks Andreas 👍
