### ISSUE TITLE
First simple product is given the name of the configurable

### ISSUE THREAD

**Issue by patrick-bigbridge** [firegento/FireGento_FastSimpleImport2#49]
Following the example for importing configurables on this page

https://github.com/firegento/FireGento_FastSimpleImport2_Demo/blob/master/Console/Command/Product/ImportConfigurable.php

I found that the name of the configurable is copied to the first simple product.

**Comment by phrench** [comment]
Code works for me. You're sure it's not your array?

**Comment by patrick-bigbridge** [comment]
Thanks for checking. I will be working on this again in a few days. I will look into it further.

**Comment by patrick-bigbridge** [comment]
I investigated the matter further and found that it was a Magento Importer bug, that occurs when the configurable SKU is an integer and the simple SKU's are extensions of this SKU.

It has been reported https://github.com/magento/magento2/issues/5547
and has a fix https://github.com/magento/magento2/pull/6446
