### ISSUE TITLE
Can not install the module via Composer

### ISSUE THREAD

**Issue by AminMemariani** [firegento/FireGento_FastSimpleImport2#5]
I'm trying to install this module: https://github.com/firegento/FireGento_FastSimpleImport2
via composer( sudo composer require firegento/fastsimpleimport2)
 but it is giving me the following error on terminal:
"[InvalidArgumentException]
Could not find package firegento/fastsimpleimport2 at any version for
your minimum-stability (alpha)
. Check the package spelling or your minimum-stability"
Any solution is appreciated.

**Comment by avstudnitz** [comment]
Have you added the repository to the composer.json? The module is not yet on packagist nor on packages.firegento.com.

**Comment by AminMemariani** [comment]
OIC, Thanks!

**Comment by arsiboo** [comment]
This is our composer.json repositories:

```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.5",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/firegento/FireGento_FastSimpleImport2.git"
        },
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.0.5",
        "composer/composer": "@alpha"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "2.3.*",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}

```

We run the following command from root of our magento installation:
`sudo composer require firegento/fastsimpleimport2`

Error we get:

> [InvalidArgumentException]                                                                            
>   Could not find package firegento/fastsimpleimport2 at any version for your minimum-stability (alpha)  
>   . Check the package spelling or your minimum-stability

How can we install this package ? Any other alternatives ?

**Comment by therouv** [comment]
Please try to add the repository:
`composer config repositories.fastsimpleimport2 vcs https://github.com/firegento/FireGento_FastSimpleImport2.git`
and then run the require command again:
`composer require firegento/fastsimpleimport2`

**Comment by arsiboo** [comment]
@therouv thanks for your response. I tried running your command but no luck.

I run this command:
`composer config repositories.fastsimpleimport2 vcs https://github.com/firegento/FireGento_FastSimpleImport2.git`

my composer.json is like this:
```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.5",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": {
        "1": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "fastsimpleimport2": {
            "type": "vcs",
            "url": "https://github.com/firegento/FireGento_FastSimpleImport2.git"
        }
    },
    "require": {
        "magento/product-community-edition": "2.0.5",
        "composer/composer": "@alpha"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "2.3.*",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}

```


the I run this command:
`composer require firegento/fastsimpleimport2`

I get the following output:

> [InvalidArgumentException]                                                                             
>   Could not find package firegento/fastsimpleimport2 at any version for your minimum-stability (alpha).  
>    Check the package spelling or your minimum-stability      
> 
>

**Comment by EliasKotlyar** [comment]
Hello arsiboo,

please try it with :
composer require firegento/fastsimpleimport2 dev-master

this should do the trick,cause it tells composer which branch to use.

Greetings
ELias

**Comment by EliasKotlyar** [comment]
Hello @arsiboo ,

Do you still have this Problem? If so,please report , and we can find a solution. Otherwise we will close this issue

Greetings
Elias

**Comment by 7ochem** [comment]
Why not publish it on Packagist?

**Comment by springerin** [comment]
+1 for tagging
we have to use specific commit but would be preferable having a tag

**Comment by kweij** [comment]
+1 for tagging

Semantic versioning is pretty awesome, join into the awesomeness and tag a release!

**Comment by Sapta34** [comment]
Can't install this on magento 2.0.10 in localhost using composer require firegento/fastsimpleimport2 dev-master. My composer.json "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "fastsimpleimport2": {
            "type": "vcs",
            "url": "https://github.com/firegento/FireGento_FastSimpleImport2.git"
        }
    },
Please help me to install this extension.

**Comment by amenk** [comment]
Is it still not on packagist? Why is that?

**Comment by avstudnitz** [comment]
@amenk It is: https://packagist.org/packages/firegento/fastsimpleimport

**Comment by amenk** [comment]
Maybe I confused this with extendedimport 💭
