### ISSUE TITLE
Rename images when importing from external URL

### ISSUE THREAD

**Issue by phrench** [firegento/FireGento_FastSimpleImport2#50]
First of all, thanks for this great extension and the demo extension with the sample code!

When importing product images from external URLs, the resulting image file name contains the domain name and path of the external URL.

Is there a way to rename the image upon importing?

**Comment by hostep** [comment]
This might be related to a bug in Magento2 itself: https://github.com/magento/magento2/issues/5306

**Comment by phrench** [comment]
Thanks for the hint.

In this case I'll change my script to first download the images to a local folder and import the locally.

**Comment by PieterCappelle** [comment]
Should be fixed. If accepted I'll create backport to 2.2 & 2.1.
https://github.com/magento/magento2/pull/12872
