### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Sapta34** [firegento/FireGento_FastSimpleImport2#51]
Can't install this on magento 2.0.10 in localhost using composer require firegento/fastsimpleimport2 dev-master. My composer.json "repositories": {
"0": {
"type": "composer",
"url": "https://repo.magento.com/"
},
"fastsimpleimport2": {
"type": "vcs",
"url": "https://github.com/firegento/FireGento_FastSimpleImport2.git"
}
},

Display the following error:
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package firegento/fastsimpleimport2 could not be found in an
y version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more det
ails.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.
Please help me to install this extension.

**Comment by sprankhub** [comment]
Sorry that no answer has been given. However, I am rather sure this is not relevant any more :)
