### ISSUE TITLE
Category import feature checking breaks with B2B versioning

### ISSUE THREAD

**Issue by brosenberger** [firegento/FireGento_FastSimpleImport2#55]
the B2B module breaks with version numbering of the standard magento community and enterprise editition as it starts with 1.0.0

therefore adding categories is not possible as for attributes the wrong entity relation id is set as table column (entity_id instead of row_id from the enterprise version)

-> \FireGento\FastSimpleImport\Model\Enterprise\VersionFeaturesFactory

**Comment by sprankhub** [comment]
If I understand correctly, this has been solved.
