### ISSUE TITLE
CategoryImport Sequence is not correctly initialized and is empty in enterprise edition

### ISSUE THREAD

**Issue by brosenberger** [firegento/FireGento_FastSimpleImport2#56]
\FireGento\FastSimpleImport\Model\Enterprise\CategoryImportVersion L57+58

Here the metadatapool and sequenceregistry is created as new object instead of using the object (with initialized data) from the context.

with an enterprise edition no correct entity_id can therefore be obtained and crashes the import

**Comment by sprankhub** [comment]
If I understand correctly, this has been fixed.
