### ISSUE TITLE
question

### ISSUE THREAD

**Issue by albalucia** [firegento/FireGento_FastSimpleImport2#6]
I’m looking at the import/export extension for Magento 2.

We are now developing our first project on 2.0 and I’m encountering some issues regarding attributes.

I was planning to upload firegento extension but need to make sure this will help me with this problem.

 When I run the export, all the attributes that I’ve manually created are exported in the same column ( in the cvs file) instead that different ones with the attribute code as title ( does this make sense to you)

 Will this extension solve this problem as well?

I look forward to your reply,

Best,

Alba

**Comment by EliasKotlyar** [comment]
Hello albalucia,

I really understand your Problem. M1 had a column for every custom attribute,but M2 has not. Instead, you will have to fill your custom attributs into the column named "additional_attributes". The attributs should be delimited by a ",". This Plugin have the same format as the csv files which you get from the import/export backend tool. You will have to manually split your custom attributes from the magento-system attributes and put your custom attributes into the additional_attributes column. 

Have a look at the demo code for a better understanding:
https://github.com/firegento/FireGento_FastSimpleImport2_Demo/tree/master/Console/Command/Product

I hope i could answer your question.

Greetings
Elias
