### ISSUE TITLE
Create attribute option on the fly

### ISSUE THREAD

**Issue by VincentMarmiesse** [firegento/FireGento_FastSimpleImport2#65]
Hello,

Is it possible to create an attribute option on the fly?
For example if I import a product with a color which does not exist, I would like Magento to create the option.

Instead I currently have the error

```
1: Begin data validation
2: Data validation failed. Please fix the following errors and upload the file again.
3: Value for 'color' attribute contains incorrect value, see acceptable values on settings specified for Admin in row(s): 1, 2, 3, 4, 5
4: Checked rows: 5, checked entities: 5, invalid rows: 5, total errors: 5
```

Is it possible to do it?

Thanks!

**Comment by amenk** [comment]
AvS_FastSimpleImport was able to do this. But you needed to set an option during import http://avstudnitz.github.io/AvS_FastSimpleImport/options.html . not sure if it is in   FastSimpleImport2 already

**Comment by avstudnitz** [comment]
It's not. It's in https://github.com/firegento/FireGento_ExtendedImport2. Haven't tested it yet though. See https://github.com/firegento/FireGento_ExtendedImport2/commit/688a803d2ade7c914428eb4488e62ebc29d017df.
