### ISSUE TITLE
Automatically create a select attribute option

### ISSUE THREAD

**Issue by VincentMarmiesse** [firegento/FireGento_FastSimpleImport2#66]
Hello,
Is it possible to automatically create a select attribute option while importing products?

For example, I have a `size` attribute which is a select attribute and I would like the import to create the options (S, M, XL etc.) if it does not exist.
Currently, it raises the following error: "Value for 'size' attribute contains incorrect value, see acceptable values on settings specified for Admin in row(s)".

Thank you!

Regards,

**Comment by EvanRijn** [comment]
This module is fixing that; https://github.com/firegento/FireGento_ExtendedImport2

**Comment by VincentMarmiesse** [comment]
Indeed, thanks!
