### ISSUE TITLE
Customers import?

### ISSUE THREAD

**Issue by VincentMarmiesse** [firegento/FireGento_FastSimpleImport2#69]
Hello,

It may be a dump question but can I import customer with the module? I don't see anything related to it in code and documentation but the description says `Wrapper for Magento 2 ImportExport functionality, which imports products and customers from arrays`.

Thank you!

**Comment by sprankhub** [comment]
This should be possible. See https://github.com/firegento/FireGento_FastSimpleImport2_Demo/blob/master/Console/Command/Customer/ImportCustomer.php.
