### ISSUE TITLE
Not setting qty attribute.

### ISSUE THREAD

**Issue by ohtaron** [firegento/FireGento_FastSimpleImport2#7]
Trying to import product data and stock data.
I use attribute qty and it is not getting saved into de DB... So, no stock, no products in frontend.

Example of attributes in product array:

`'sku' => $codigo_proveedor.$articulo->codigo,
                'categories' => $categorias_str,
                'attribute_set_code' => 'Default',
                'product_type' => 'simple',
                'product_websites' => 'base',
                'additional_attributes' => "ean=".$articulo->ean.",talla=".$articulo->talla.",hashtalla=".$articulo->hashtalla.",novedad=".$articulo->novedad.",promocion=".$articulo->promocion.",reponer=".$articulo->reponer.",precio_comercio_a=".$articulo->precio_comercio_a,
                'name' => $articulo->descripcion,
                'price' => $articulo->precio_recomendado,
                'is_in_stock' => 1,
                'qty' => intval($articulo->stock_disponible),
                'base_image'=>$imagen_base,
                'small_image'=>$articulo->imagen_gr,
                'thumbnail_image'=>$articulo->imagen_bu,
                'additional_images'=>$imagenes_str,
                'visibility' => 'Catalog, Search',
                //'tax_class_name' => $articulo->iva,
                //'manufacturer' => $articulo->fabricante,
                'description' => $articulo->explicacion,`

Thanks for your help.

**Comment by EliasKotlyar** [comment]
Hello ohtaron,

can you please provide a filled out array which you are trying to import? I cannot reproduce this issue, if i see a lot of variables inside the code.

Also consider having a look at the examples: 
https://github.com/firegento/FireGento_FastSimpleImport2_Demo/tree/master/Console/Command/Product

Greetings
Elias

**Comment by ohtaron** [comment]
This is an example array extracted with var_dump:

> array(1) {
>   [0]=>
>   array(16) {
>     ["sku"]=>
>     string(9) "1100089"
>     ["categories"]=>
>     string(93) "Default Category/BEBIDAS/ACCESORIOS/PAJITAS,Default Category/BEBIDAS/ACCESORIOS/COMPLEMENTOS,"
>     ["attribute_set_code"]=>
>     string(7) "Default"
>     ["product_type"]=>
>     string(6) "simple"
>     ["product_websites"]=>
>     string(4) "base"
>     ["additional_attributes"]=>
>     string(124) "ean=8433774532736"
>     ["name"]=>
>     string(24) "PAJITAS SURTIDAS COLORES"
>     ["price"]=>
>     string(6) "1.4700"
>     ["qty"]=>
>     int(7)
>     ["base_image"]=>
>     string(55) "lg/lg_1100089_0.jpg"
>     ["small_image"]=>
>     string(53) "gr/gr_1100089.jpg"
>     ["thumbnail_image"]=>
>     string(53) "bu/bu_1100089.jpg"
>     ["additional_images"]=>
>     string(55) "lg/lg_1100089_0.jpg"
>     ["visibility"]=>
>     string(15) "Catalog, Search"
>     ["description"]=>
>     string(357) "Los productos PRIVILEGE son los preferidos por los que desean equipar la cocina con los mejores complementos para el menaje. Accesorios para cocinar y ordenar tu cocina, para la mesa, para el horno, el fogon y la vitroceramica, para el desayuno, la comida y la cena. En cualquier rincón de tu cocina y en cualquier momento del día PRIVILEGE está contigo."
>   }
> }

Note: the only attribute that is not loading into de magento DB is "qty".

And yes, I have checked the examples, but no one of them is using stock data...

Lots of Thanks.

**Comment by EliasKotlyar** [comment]
Hello ohtaron,

I tried your array, but still cannot reproduce. The Qty is importing well into the Database in my test-machine. Can you please check if the normal "import" using CSV-Files is working for you? 

If its working,please provide following information:
1. PHP Version
2. Magento Version
3. PHP.ini settings
4. which modules do you have enabled on your magento?
4. Did you encountered any problems during installation of magento?

If its not working, its been likely that you have a problem with your magento installation. try to install again and see if it helps


Greetings
Elias

**Comment by ohtaron** [comment]
Finally I found the problem, I had to format correctly the qty value:

> 'qty'=>floatval($quantity.".0000"),

Thanks for your help!
