### ISSUE TITLE
 Uncaught Error: Class 'FireGento\FastSimpleImport\Model\Import\Config' 

### ISSUE THREAD

**Issue by sunilit42** [firegento/FireGento_FastSimpleImport2#72]
Hello,

while category import we are facing below issue

 Uncaught Error: Class 'FireGento\FastSimpleImport\Model\Import\Config' not found in /var/www/html/vendor/firegento/fastsimpleimport/Model/Import/Category.php:559

**Comment by pratikrgandhi** [comment]
Add below code to FireGento_FastSimpleImport2/Model/Import/Category.php

=> use FireGento\FastSimpleImport\Helper\Config as Config;

**Comment by haelbichalex** [comment]
Got this error as well. Using above code fixed it for me.

**Comment by sprankhub** [comment]
This should be fixed thanks to @amenk.
