### ISSUE TITLE
install ok, but error when enabling module

### ISSUE THREAD

**Issue by HamiltonWang** [firegento/FireGento_FastSimpleImport2#74]
version:magento 2.2
>>  php ./bin/magento module:enable --clear-static-content   FireGento_FastSimpleImport
[Magento\Framework\Exception\FileSystemException]  
  The file "/composer.json" doesn't exist

**Comment by BorisovskiP** [comment]
Tested on Magento Version : 2.3.5-p1, module version 1.3.1, the issue could not be reproduced.
