### ISSUE TITLE
Import process is too slow

### ISSUE THREAD

**Issue by Nehace40** [firegento/FireGento_FastSimpleImport2#77]
Import process is too slow
In csv i have sku and one custom attribute and number of 24000 sku are in csv

10000 row take 4-5 hours to execute how can i reduce it.

**Comment by Nehace40** [comment]
Another 3rd party module is a reason for slow import

**Comment by dzschille** [comment]
@Nehace40 which 3rd party module was it? I have to search for our bottleneck.

**Comment by Nehace40** [comment]
RWE AEImporter
