### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by rainer1108** [firegento/FireGento_FastSimpleImport2#8]
This line asks for user an password:
composer require firegento/extendedimport dev-master

Which user/password should i use?

Thanks

**Comment by EliasKotlyar** [comment]
Hello Rainer,

I assume that it asks you for the Github Password. If it doesnt help,please provide a full Log of the Commands which are stated there.

Greetings
Elias

**Comment by EliasKotlyar** [comment]
Hello @rainer1108 

Do you still have this Problem? If so,please report , and we can find a solution. Otherwise we will close this issue

Greetings
Elias
