### ISSUE TITLE
Please tag a stable release

### ISSUE THREAD

**Issue by amenk** [firegento/FireGento_FastSimpleImport2#85]
see also

https://github.com/firegento/FireGento_FastSimpleImport2/pull/84

What is holding us back :D ?

**Comment by EliasKotlyar** [comment]
Hello @amenk ,

From my side: The lack of credentials for the packagist website.

@avstudnitz: Do you have the credentials?

Greatings
Elias

**Comment by avstudnitz** [comment]
@EliasKotlyar No I don't, but it shouldn't be necessary, as the repository already has a running integration with packagist. Just create a new tag, and it should automatically be published by packagist too.

**Comment by amenk** [comment]
@EliasKotlyar Can you create a tag?
