### ISSUE TITLE
Question: What is the prefered way choose to import products? Load Products from an mysql Temp table? Create an CSV with all Products for the import? 

### ISSUE THREAD

**Issue by ankit-sf** [firegento/FireGento_FastSimpleImport2#89]
Question: What is the prefered way choose to import products? Load Products from an mysql Temp table? Create an CSV with all Products for the import? 
also how could we manage timeouts for large data imports say 50k- 100k products?

any suggestion is welcome.

Thanks

**Comment by sprankhub** [comment]
Where your data comes from is totally up-to-you. I often see CSV sources, but SQL-sources or API-sources (or whatever sources) are possible as well.
Talking about timeouts, I think you either need to increase them or import in bunches.
