### ISSUE TITLE
import.xml invalid?

### ISSUE THREAD

**Issue by pquerner** [firegento/FireGento_FastSimpleImport2#9]
Magento 2.2.0-dev throws this error in developer mode.

```
Invalid XML in file /home/pascal/FireGento_FastSimpleImport2/etc/import.xml:
Element 'entity', attribute 'model': [facet 'pattern'] The value 'FireGento\FastSimpleImport2\Import\Category' is not accepted by the pattern '[A-Za-z_\\\\]+'.
Line: 9

Element 'entity', attribute 'model': 'FireGento\FastSimpleImport2\Import\Category' is not a valid value of the atomic type 'modelName'.
Line: 9
```

(called via Demo module to import sample simple products; the upgrade command (initial installation) went fine)

**Comment by pquerner** [comment]
Theres an magento bug which willl invalide module names (from Import/Exporter) containing a number, see this PR by Nils. https://github.com/magento/magento2/pull/5420

Removing the file (because category import wont work as of now) fixes the problem, obviously..

**Comment by EliasKotlyar** [comment]
-> Fixed this issue by renaming the module
