### ISSUE TITLE
Is module compatible with Magento 2.3

### ISSUE THREAD

**Issue by ankit-sf** [firegento/FireGento_FastSimpleImport2#91]
will this module be compatible with Magento 2.3
and will it support field like "Empty attribute value constant" in CSV

Thanks

**Comment by mironsoft75** [comment]
Can I import without price, is this also supported? If a price was manually changed in the backend, I do not want to change it by update. If a miss in the CSV is empty, the values in the database should not change. Is that already so?
Thanks

**Comment by skynixukraine** [comment]
How is this going?

**Comment by sprankhub** [comment]
Yes, it is compatible with 2.3 and even with 2.4.
