### ISSUE TITLE
How can i import simple_links and downloadable_links of downloadable products?

### ISSUE THREAD

**Issue by ahmadwaliesipick** [firegento/FireGento_FastSimpleImport2#96]
i want to import downloadable products, which have multiple sample_links and downloadable_links, My Magento app is multi store site.
like i have 7 multistore/multilingual, each product belongs to different or same stores the title and description of each product is different with each store.
so once import a single product i am doing like this:
[Sample code](https://gist.github.com/ahmadwaliesipick/36e11b2e2c28ab09ea9ef3b33c11c2e7)

So how can i add the sample_links and downloadable_links for downloadable products?

**Comment by ahmadwaliesipick** [comment]
@avstudnitz  could you please reply on this issue?

**Comment by avstudnitz** [comment]
Sorry, no idea. This is a question about the Magento ImportExport functionality which is being used and wrapped by FastSimpleImport. I'd suggest that you ask that question on https://magento.stackexchange.com/.
